name: MenuTTS
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    macOS: '13.0'

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.example.MenuTTS
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1

configs:
  Debug: debug
  Release: release

targets:
  MenuTTS:
    type: application
    platform: macOS
    deploymentTarget: '13.0'
    sources:
      - path: .
        excludes:
          - "project.yml"
          - "Makefile"
          - "Info.plist"
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        SWIFT_VERSION: 5.9
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
